import {
  Activity,
  Anchor,
  ArrowBigRight,
  Atom,
  Battery,
  BatteryCharging,
  Beaker,
  Bike,
  BookOpen,
  Cable,
  Calculator,
  Camera,
  Car,
  Check,
  CircuitBoard,
  Clock,
  Cog,
  Dna,
  Droplet,
  Earth,
  Eye,
  Flame,
  FlaskConical,
  Gauge,
  GraduationCap,
  Heart,
  Hourglass,
  Infinity as InfinityIcon,
  Info,
  Lightbulb,
  Magnet,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  Orbit,
  Pencil,
  Plane,
  Plug,
  Radio,
  Rocket,
  Ruler,
  Satellite,
  Scale,
  Sigma,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Target,
  Telescope,
  TestTube,
  Thermometer,
  Timer,
  TrainFront,
  TriangleAlert,
  Volume2,
  Weight,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Icônes intégrées (lucide, licence ISC), choisies pour la physique-chimie. */
export const ICON_CATALOG: Readonly<Record<string, LucideIcon>> = {
  atom: Atom,
  magnet: Magnet,
  zap: Zap,
  lightbulb: Lightbulb,
  battery: Battery,
  batteryCharging: BatteryCharging,
  plug: Plug,
  cable: Cable,
  circuit: CircuitBoard,
  radio: Radio,
  flask: FlaskConical,
  beaker: Beaker,
  testTube: TestTube,
  microscope: Microscope,
  dna: Dna,
  thermometer: Thermometer,
  flame: Flame,
  snowflake: Snowflake,
  droplet: Droplet,
  wind: Wind,
  sun: Sun,
  moon: Moon,
  earth: Earth,
  orbit: Orbit,
  satellite: Satellite,
  rocket: Rocket,
  telescope: Telescope,
  sparkles: Sparkles,
  gauge: Gauge,
  timer: Timer,
  clock: Clock,
  hourglass: Hourglass,
  ruler: Ruler,
  scale: Scale,
  weight: Weight,
  calculator: Calculator,
  sigma: Sigma,
  infinity: InfinityIcon,
  activity: Activity,
  volume: Volume2,
  music: Music,
  mic: Mic,
  eye: Eye,
  camera: Camera,
  car: Car,
  bike: Bike,
  train: TrainFront,
  plane: Plane,
  anchor: Anchor,
  mountain: Mountain,
  cog: Cog,
  target: Target,
  arrow: ArrowBigRight,
  check: Check,
  cross: X,
  warning: TriangleAlert,
  info: Info,
  star: Star,
  heart: Heart,
  pencil: Pencil,
  book: BookOpen,
  graduation: GraduationCap,
};

export const ICON_IDS = Object.keys(ICON_CATALOG);
